name: goreleaser

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.BW_HUBOT_GITHUB_ACTION_TOKEN }}
          repository: BrandwatchLtd/slipstream

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/kuber-cli
        env:
          GITHUB_TOKEN: ${{ secrets.BW_HUBOT_GITHUB_ACTION_TOKEN }}
